#model params
model_name : cosloss
backbone: Resnet50
headtype: CosHead
loss    : Cosloss
#-----------

image_size: 112
embd_size: 512
class_num: 5000
sample_num: 339709

##-------------------
## hyper params
weight_decay: !!float 5e-4
logits_scale: 64.0
logits_margin: 0.4

##optimizer
momentum: 0.9
base_lr : 0.04
decay   : True
lr_steps: [40000, 60000, 80000]
lr_values: [0.004, 0.0012, 0.0004]

##--------------------
# run params
batch_size: 64
init_epoch: 1
epoch_num: 25
step_per_save: 5000

## # paths <SHOULD JUST CHANGE TRAIN DATA!>

train_data: "C:/Users/84982/Documents/GitHub/arcface_experiment/data/5kdataset.tfrecord"
val_data: {'lfw': 'C:/Users/84982/Documents/GitHub/arcface_experiment/data/test_data', 'cfp_ff': '/home/nhuntn/K64/FaceRecognition/data/cfp_ff', 'cfp_fp': '/home/nhuntn/K64/FaceRecognition/data/cfp_fp', 'agedb_30':'/home/nhuntn/K64/FaceRecognition/data/agedb_30', 'vgg2_fp': '/home/nhuntn/K64/FaceRecognition/data/vgg2_fp'}
save_dir : 'C:/Users/84982/Documents/GitHub/arcface_experiment/save'